### ISSUE TITLE
Setup Streamlit sharing

### ISSUE THREAD

**Issue by haonanw98** [CMU-IDS-2020/a3-ddl-fighter#1]
Dear TAs, please add our repo to Streamlit sharing and then respond to this issue with the URL to the deployed application.
Please run pip install requirements and also please use yelp.py as the main file.
Thanks a lot!

**Comment by domoritz** [comment]
please rename yelp.py to streamlit_app.py and then it will work.

**Comment by haonanw98** [comment]
Should the link be https://share.streamlit.io/cmu-ids-2020/a3-ddl-fighter?

**Comment by aditya5558** [comment]
Here's your app: https://share.streamlit.io/cmu-ids-2020/a3-ddl-fighter

**Comment by haonanw98** [comment]
I see a 404? What could be the problem?

**Comment by domoritz** [comment]
Here is your link https://share.streamlit.io/cmu-ids-2020/a3-ddl-fighter/yelp.py.

**Comment by haonanw98** [comment]
Thank you so much!
