### ISSUE TITLE
Problem with the deployment

### ISSUE THREAD

**Issue by haonanw98** [CMU-IDS-2020/a3-ddl-fighter#2]
Hi,
We are playing with our Streamlit sharing and suddenly it stuck. We try to update something to renew the page, however, it says that the app is updating and stuck there for 10 minutes.
Could you please tell us how to solve it?
Thanks,
Haonan

**Comment by domoritz** [comment]
Check the logs. Unfortunately, it's a bit late for us to help with the deployment.

**Comment by haonanw98** [comment]
Actually, it does pretty well at the very beginning. So I think if you simply restart it, it will work well.

**Comment by domoritz** [comment]
I rebooted your app

**Comment by haonanw98** [comment]
Thanks a lot! It works.

**Comment by domoritz** [comment]
Great
